version: "3"
services:
  database:
#   na wersji mongo:3.2.4 nie dziala
    image: mongo:4.4.3
#    nie potrzebne
#    container_name: database
    ports:
      - 27017:27017
#    powoduje blad
#    command: --smallfiles
  users:
    image: users
    ports:
      - 8080:8080
    links:
      - database
  job-offers:
    image: job-offers
    ports:
      - 8081:8081
    links:
      - database