version: "3.8"
services:
  database:
    image: mongo:4.4.3
    ports:
      - 27017:27017
  users:
    build: ./userservice
    ports:
      - 8080:8080
    links:
      - database
  job-offers:
    build: ./jobofferservice
    ports:
      - 8081:8081
    links:
      - database