package com.ledzion.jobofferservice.model;

import lombok.Data;

import java.time.LocalDate;

@Data
public class JobOfferDto {

    //TODO: id to be generated by database and not to be provided in http request
    private String id;

    private String category;

    private LocalDate startDate;

    private LocalDate endDate;

    private String employerName;
}
